language: node_js
node_js:
- '0.11'
- '0.10'
env:
  global:
  - secure: bsyn+GhN24JCsY6LXeiwCy6fNKg2qizCZmebWEPEX0yUITwIKBszImrCe7b9j47IZ1SxnXHMKBesdkXKsgzqCZ+hDs/dqG18MIdUi2A4VbbZSWNWtCMin3FOnW9O5zSZ6+Jo0XrwxUo2jaOdr23TSt2QE1ugkcHlhJhFe6e3XR8=
  - secure: c6khfEl4er2obUe9eP4EIl4yVjJWyYtVVx8yHkDOqrYpK8oa10LfcE4XV+/oxZOni7AOTGFwrgrjXZDUVy0EJaEzYFx0xW7gi1P7EyCVP8WFb9upfyHz46EclGTJ3lM+1zvyR3GjMWo+XqXopo1Z+iUH9uwtgE8cictzl5PYkUA=
